# Generated by Django 3.1.3 on 2020-11-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_material_order'),
        ('products', '0002_auto_20201127_1432'),
    ]

    operations = [
    ]
