# Generated by Django 3.1.3 on 2020-11-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
        ('products', '0003_product_image'),
    ]

    operations = [
    ]
